pipeline:
  clone:
    image: plugins/git
    depth: 2

  security checking:
    image: alpine
    commands:
      - echo -e "$MD5_LIST" | md5sum -wc

  coding style:
    image: grachev/php-cs-fixer
    commands:
      - >-
        php-cs-fixer fix
        --config=.php_cs.dist
        --verbose
        --dry-run
        --using-cache=no
        --path-mode=intersection
        `git diff --name-only --diff-filter=ACMRTUXB HEAD^`

  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - >-
        docker build -t "${HUB_REPO}:${DRONE_BUILD_NUMBER}"
        --file docker/Dockerfile
        --label branch="${DRONE_COMMIT_BRANCH}"
        --build-arg GITHUB_AUTH_TOKEN="$GITHUB_AUTH_TOKEN"
        --build-arg APP_VERSION="$DRONE_BUILD_NUMBER" .

  phpstan:
    image: ${HUB_REPO}:${DRONE_BUILD_NUMBER}
    commands:
      - cd "$APP_DIR"
      - phpstan analyse --level 5 --configuration phpstan.neon --no-progress src tests

  symfony requirements:
    image: ${HUB_REPO}:${DRONE_BUILD_NUMBER}
    commands:
      - /docker-entrypoint.sh symfony_requirements
    environment:
      APP_ENV: test
      APP_DEBUG: 0
      MIGRATION: false

  yaml lint:
    image: ${HUB_REPO}:${DRONE_BUILD_NUMBER}
    commands:
      - /docker-entrypoint.sh console lint:yaml etc
    environment:
      APP_ENV: test
      APP_DEBUG: 0
      MIGRATION: false

  doctrine validation:
    image: ${HUB_REPO}:${DRONE_BUILD_NUMBER}
    commands:
      - while ! nc -z 127.0.0.1 3306; do sleep 1; done
      - /docker-entrypoint.sh console doctrine:schema:validate --skip-sync
    environment:
      APP_ENV: test
      APP_DEBUG: 0
      MIGRATION: false

  phpunit:
    image: ${HUB_REPO}:${DRONE_BUILD_NUMBER}
    commands:
      - /docker-entrypoint.sh phpunit
    environment:
      APP_ENV: test
      APP_DEBUG: 0
      MIGRATION: false

  publish:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u"$HUB_LOGIN" -p"$HUB_PASSWORD"
      - docker push "${HUB_REPO}:${DRONE_BUILD_NUMBER}" > /dev/null
      - >+
        if [ "master" == "$DRONE_COMMIT_BRANCH" ]; then
          docker tag "${HUB_REPO}:${DRONE_BUILD_NUMBER}" "${HUB_REPO}:latest"
          docker push "${HUB_REPO}:latest" > /dev/null
          docker rmi --force "${HUB_REPO}:latest"
        fi
    when:
      event: push

  clean:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - >+
        if [ "success" == "$DRONE_BUILD_STATUS" ] && [ "push" == "$DRONE_BUILD_EVENT" ]; then
          docker rmi `docker images -q --filter before="${HUB_REPO}:${DRONE_BUILD_NUMBER}" --filter label="branch=$DRONE_COMMIT_BRANCH" "${HUB_REPO}"` || true
        else
          docker rmi --force "${HUB_REPO}:${DRONE_BUILD_NUMBER}"
        fi
    when:
      status: [ failure, success ]

  deploy:
    image: appleboy/drone-ssh
    host: ${DEPLOY_HOST}
    username: ${DEPLOY_USER}
    key: ${DEPLOY_KEY}
    script:
      - docker pull "${HUB_REPO}:${DRONE_BUILD_NUMBER}"
      - docker service update --image "${HUB_REPO}:${DRONE_BUILD_NUMBER}" "${DEPLOY_SERVICE}"
      - >-
        docker rmi
        `docker images -q --filter "before=${HUB_REPO}:${DRONE_BUILD_NUMBER}" "${HUB_REPO}"`
        2> /dev/null || true
    when:
      branch: master

services:
  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ALLOW_EMPTY_PASSWORD: true
