version: '2'

services:
  app:
      build:
          dockerfile: Dockerfile_dev
          context: .
      hostname: service.local
      volumes:
          - ./:/usr/local/app
      depends_on:
          - db

  db:
      image: mariadb
      hostname: db.service.local
      volumes:
          - mysql-db:/var/lib/mysql
      environment:
          MYSQL_DATABASE: db
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

volumes:
  mysql-db:
    driver: local
