services:
    app.event_listener.response:
        class: AppBundle\EventListener\ResponseListener
        arguments:
            - '@serializer'
        tags:
          - { name: kernel.event_subscriber }

    app.event_listener.exception:
        class: AppBundle\EventListener\ExceptionListener
        arguments:
            - '%kernel.environment%'
        tags:
          - { name: kernel.event_subscriber }
