services:
    app.request.request_factory:
        class: AppBundle\Request\RequestFactory

    app.request.param_converter.uuid:
        class: AppBundle\Request\ParamConverter\UuidConverter
        tags:
            - { name: request.param_converter }

    app.request.param_converter.request:
        class: AppBundle\Request\ParamConverter\RequestConverter
        arguments:
            - '@app.request.request_factory'
            - '@validator'
        tags:
            - { name: request.param_converter }
