imports:
    - { resource: controllers.yml }
    - { resource: listeners.yml }
    - { resource: normalizers.yml }

services:
    app.doctrine.bundle_naming_strategy:
        class: AppBundle\Doctrine\BundleNamingStrategy

    app.monolog.uuid_processor:
        class: AppBundle\Monolog\UuidProcessor
        arguments:
            - "@request_stack"
        shared: false
        tags:
            - { name: monolog.processor }
